### ISSUE TITLE
CloudFormation failing at Instance Healthcheck

### ISSUE THREAD

**Issue by guybumbling** [aws-quickstart/quickstart-alfresco-one#10]
I am attempting to use the Alfresco quickstart out of the box.  I am getting all the way through to creation of the RDSDB and then the server and index instances come up pending healthy check.  

In the logs:
	13:45:54 UTC-0700	CREATE_FAILED	AWS::CloudFormation::Stack	AlfrescoStack	Embedded stack arn:aws:cloudformation:us-west-2:346147488134:stack/alf-dev-cluster-usw-2-AlfrescoStack-15T687DXAHT2Z/7701d5f0-e985-11e6-a255-50a68a0e32f2 was not successfully created: The following resource(s) failed to create: [IndexAutoScalingGroup, AlfrescoAutoScalingGroup].

The instances do spin up and do show reporting in the ELB and as Status: available. 
- The healthcheck never completes successfully (only seeks for two 30 second cycles) and then CloudFormation sees this as a failure and terminates, destroying the entire stack as it does.  
- In fact, the ELB Monitor does not report healthy or unhealthy in the charts even though the instances are attached to the ELB and showing available

**Comment by toniblyx** [comment]
Hi @guybumbling thanks for reporting your issue. I'm wondering if you made the step to agree with the Alfresco One AMI conditions and also you used a valid license (cluster enabled). Asking to AWS support they probably can give you more details on why the autoscaling groups failed.

**Comment by guybumbling** [comment]
Yes, I did complete the 'Agree' step and received the license URL from our Customer Service team.  I will double-check the license with them again. 
- Two more general questions/comments for you:
1) Why two bastion hosts and not a single bastion spanning both AZs?
2) I did attempt to clone your develop branch and also attempted to download the zip. Not all files came down.

Great roll-out with this!  I am looking forward to getting it up and running.  I was just about to embark on putting together my own cluster for alfresco from scratch. You guys are making this way easier on me. Thanks!

**Comment by toniblyx** [comment]
If you have agreed with the terms and have a proper license it might be something different, looking at the error of the Alfresco Stack you probably can see more details on why IndexAutoScalingGroup, AlfrescoAutoScalingGroup are failing.

To change the template you only need to download the alfresco-one-master.template and alfresco-one.template

alfresco-one-master.template is the one that calls for VPC, Bastion and Alfresco stacks, you only will need to change the URL of the Alfresco stack to point to yours.

alfresco-one.template, you can do any change you need but remember that any alfresco configuration is done underneath with chef.

We use the official AWS VPC and Bastion stack, it is good practice to have a bastion available on each AZ for redundancy.

**Comment by santiagocardenas** [comment]
One thing to add to Toni's comments.

You can fork the repository to make it your own. Also, when you want to capture all the assets in the repo, you can clone using the --recursive option to pull all the submodules consumed from other repos.

GitHub has a limitation on their auto-generated zip file which doesn't gather the submodules referenced in a repository.

Once, you have all the files, you can modify the Quick Start and push it to your own public S3 bucket in us-east-1 or modify the S3 url mappings to your bucket's region.

If you want as well, you can contribute enhancements back into this repo via a pull request.
